# Generated by Django 4.2.30 on 2026-06-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(choices=[('$', 'Dollar ($)'), ('₹', 'Indian Rupee (₹)'), ('€', 'Euro (€)'), ('£', 'British Pound (£)'), ('¥', 'Yen / Yuan (¥)'), ('₩', 'Korean Won (₩)'), ('₽', 'Russian Ruble (₽)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('R$', 'Brazilian Real (R$)')], default='$', max_length=8)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
