# Generated by Django 4.2.30 on 2026-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AddField(
            model_name='storesettings',
            name='from_email',
            field=models.EmailField(default='noreply@ruralconversations.com', help_text='Sender address used for order emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown top-left in the navbar. A transparent PNG with light artwork works best on the dark navbar. Leave blank to show the site name as text.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notification_email',
            field=models.EmailField(default='mail@ruralconversations.com', help_text='Store address that receives a copy of each order.', max_length=254),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='site_name',
            field=models.CharField(default='Rural Conversations', max_length=100),
        ),
    ]
