# Generated by Django 4.2.30 on 2026-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_storesettings_options_storesettings_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser-tab icon. A small square PNG (e.g. 32×32 or 48×48) is recommended; .ico also works.', null=True, upload_to='site/'),
        ),
    ]
