# Generated by Django 4.2.30 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='paypal_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PayPal client id'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='paypal_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PayPal secret'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='razorpay_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay key id'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='razorpay_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Razorpay key secret'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe publishable key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe secret key'),
        ),
    ]
