# Generated by Django 4.2.30 on 2026-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storesettings_paypal_publishable_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='paypal_enabled',
            field=models.BooleanField(default=False, verbose_name='PayPal enabled'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='razorpay_enabled',
            field=models.BooleanField(default=True, verbose_name='Razorpay enabled'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='stripe_enabled',
            field=models.BooleanField(default=False, verbose_name='Stripe enabled'),
        ),
    ]
