# Generated by Django 4.2.30 on 2026-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storesettings_paypal_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='currency_code',
            field=models.CharField(default='USD', help_text='ISO code used to charge customers, e.g. USD, INR, EUR, GBP, JPY. (Razorpay supports INR primarily.)', max_length=3),
        ),
    ]
