# Generated by Django 4.2.30 on 2026-06-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_storesettings_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='paypal_sandbox',
            field=models.BooleanField(default=True, help_text='On = PayPal sandbox (testing). Turn off for live payments; must match the type of PayPal keys you entered.', verbose_name='PayPal sandbox mode'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='from_email',
            field=models.EmailField(default='noreply@example.com', help_text='Sender address used for order emails.', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='notification_email',
            field=models.EmailField(default='orders@example.com', help_text='Store address that receives a copy of each order.', max_length=254),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='site_name',
            field=models.CharField(default='My Store', max_length=100),
        ),
    ]
