# Generated by Django 4.2.30 on 2026-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_backfill_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
